config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'guides#index'
  resources :guides, only: [:index, :new, :create]
  resources :notes, param: :character do
    resources :items
    resources :lists, only: [:index, :new, :create, :update, :destroy]
    resources :logs, only: [:index, :show]
    resources :reserves, only: [:index, :new, :create, :show, :update, :destroy]
    resources :messages, only: :index
  end
  resources :users, only: [:edit, :update]
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :note
  belongs_to :item
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @note = Note.find_by(character: params[:note_character])
    @lists = List.where(note_id: @note.id)
    @list = List.new
  end

  def new 
    @list = List.new
    @note = Note.find_by(character: params[:note_character])
  end

  def create
    @list = List.new(list_params)
    @note = Note.find_by(character: params[:note_char])
    if @list.save
      redirect_to note_lists_path(@note.character)
    else
      render :new
    end
  end

  def update
    @list = List.find(params[:id])
    @note = Note.find_by(character: params[:note_character])
    new_log
    if @log.save
      @list.destroy
      redirect_to note_lists_path(params[:note_character])
    end
  end

  def destroy
    @list = List.find(params[:id])
    @note = Note.find_by(character: params[:note_char])
    @list.destroy
    redirect_to note_lists_path(params[:note_character])
  end

  private
  def list_params
    params.permit(:item_id).merge(note_id: params[:note_character])
  end
  
  def new_log
    @log = Log.new
    @log.name = @list.item.name
    @log.price = @list.item.price
    @log.count = @list.item.count
    @log.condition = @list.item.condition
    @log.memo = @list.item.memo
    @log.buyer = current_user.nickname
    @log.note_id = @list.item.note_id
    @log.user_id = @list.item.user_id
  end

  def delete_item
        params[:itemcheck].each do | di1,di2 |
      if di2 == "1"
        @list = Lint.find_by(item_id: di1)
        @list.destroy
      end
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with model: [note, item], local: true do |f|%>

  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, id:"item_name" %>
  </div>

  <div class="field">
    <%= f.label :price, "価格" %><br />
    <%= f.text_field :price, class: :form__text, id:"item_price" %>
  </div>

  <div class="field">
    <%= f.label :count, "個数" %><br />
    <%= f.text_field :count, class: :form__text, id:"item_count" %>
  </div>

  <div class="field">
    <%= f.label :condition, "条件" %><br />
    <%= f.text_field :condition, class: :form__text, id:"item_condition" %>
  </div>

    <div class="field">
    <%= f.label :memo, "備考" %><br />
    <%= f.text_area :memo, class: :form__text, id:"item_memo" %>
  </div>

   <div class="field">
    <%= f.label :image, "アイテムの画像" %><br />
    <%= f.file_field :image, id:"item_image" %>
  </div>
  <input name="note_char" type="hidden" value=<%= note.character %>>
  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<tr>
<%# <td><%= check_box "itemcheck", "#{list.item.id}" %><%# </td> %>
  <td><% if list.item.image.attached? %>
        <%= link_to image_tag(list.item.image, class: :card__img ), note_item_path(id: list.item.id)  %>
      <% else %>
        <%= image_tag '/images/noimg.png' %>
      <% end %></td>
  <td><%= "#{list.item.name}" %></td>
  <td><%= "#{list.item.price}" %></td>
  <td><%= "#{list.item.count}" %></td>
  <td><%= "#{list.item.condition}" %></td>
  <td><%= "#{list.item.memo}" %></td>
<%#  <td><%= link_to '詳細', note_list_path(id: list.id) %><%# </td> %>
  <td><%= link_to '完了', note_list_path(id: list.id), method: :patch %></td>
  <td><%= link_to '取消', note_list_path(id: list.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<tr>

app/views/lists/_splist.html.erb
<tr>
<%#  <td><%= check_box "itemcheck", "#{list.item.id}" %><%#</td> %>
  <td rowspan="7"><% if splist.item.image.attached? %>
        <%= link_to image_tag(splist.item.image, class: :card__img ), note_item_path(id: splist.item.id)  %>
      <% else %>
        <%= image_tag '/images/noimg.png' %>
      <% end %></td>
  <tr><td><%= "名前" %></td><td><%= "#{splist.item.name}" %></td></tr>
  <tr><td><%= "金額" %></td><td><%= "#{splist.item.price}" %></td></tr>
  <tr><td><%= "個数" %></td><td><%= "#{splist.item.count}" %></td></tr>
  <tr><td><%= "条件" %></td><td><%= "#{splist.item.condition}" %></td></tr>
  <tr><td><%= "メモ" %></td><td><%= "#{splist.item.memo}" %></td></tr>
<%#  <td><%= link_to '詳細', note_list_path(id: list.id) %><%# </td> %>
  <tr><td><%= link_to fa_icon("check-square 2x"), note_list_path(id: splist.id), method: :patch %></td>
  <td><%= link_to fa_icon("window-close 2x"), note_list_path(id: splist.id), method: :delete, data: { confirm: 'リストから削除しますか？' } %></td>
</tr>
<tr><td colspan="3"></td></tr>

app/views/lists/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規アイテム投稿</h2>
        <%= render partial: "form", locals: { note: @note, item: @item } %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<main class="main">
  <div class="inner">
  <h1><%= "#{@note.list_name}" %></h1>
  <% if @lists == [] %>
    <div class="none_item">
    <p>登録アイテムがありません。</p>
    </div>
    <% else %>
    <table class="pc_table">
      <thead>
        <tr>
<%#       <th>選択</th> %>
          <th>画像</th>
          <th>名前</th>
          <th>金額</th>
          <th>個数</th>
          <th>条件</th>
          <th>備考</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <div>
          <%= render partial: 'list', collection: @lists %>
        </div>
      </tbody>
    </table>
        <table class="sp_table">
      <thead>
        <tr>
<%#       <th>選択</th> %>
          <th>画像</th>
          <th colspan="2">情報</th>
        </tr>
      </thead>
      <tbody>
        <div>
          <%= render partial: 'splist', collection: @lists %>
        </div>
      </tbody>
    </table>
    <% end %>
  </div>
</main>

<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <% if @note.items == [] %>
        <h2 class="page-heading">まずはアイテム登録をしましょう</h2>
        <div class="greeting">
          <%= link_to new_note_item_path(@note.character) do %>
            <input type="submit" value="アイテム登録" class="sub__btn form__btn">
          <% end %>
        </div>
      <% else %>
        <h2 class="page-heading">新規リスト登録</h2>
        <%=form_with model: [@note, @list], local: true do |f|%>
          <select name="item_id">
          <option value="">登録するアイテムを選択してください</option>
          <% Item.where(note_id: @note.id).each do |item| %>
            <option value=<%= item.id %>><%= item.name %></option>
          <% end %>
          </select>
          <input name="note_char" type="hidden" value=<%= @note.character %>>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @item.name %>
      </p>
        <% if user_signed_in? && current_user.id == @item.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_note_item_path(@item.id), class: :prototype__btn %>
          <%= link_to "削除する", note_item_path(@item.id), method: :delete, class: :prototype__btn %>
        </div>
        <% end %>
      <div class="prototype__image">
        <% if @item.image.attached? %>
        <%= link_to image_tag(@item.image), root_path  %>
      <% else %>
        <%= image_tag "/images/noimg.png" %>
      <% end %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title"><%= "金額：#{@item.price}" %></p>
          <p class="detail__title"><%= "個数：#{@item.count}" %></p>
          <p class="detail__title"><%= "条件：#{@item.condition}" %></p>
          <p class="detail__title"><%= "備考：#{@item.memo}" %></p>
          </p>
          <%= link_to "一覧へ戻る", note_items_path(@item.note.character)  %>
        </div>
      </div>
    </div>
  </div>
</main>