config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'guides#index'
  resources :guides, only: [:index, :new, :create]
  resources :notes, param: :character do
    resources :items
    resources :lists, only: [:index, :new, :create, :update, :destroy]
    resources :logs, only: [:index, :show]
    resources :reserves, only: [:index, :new, :create, :show, :update, :destroy]
    resources :messages, only: :index
  end
  resources :users, only: [:edit, :update]
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_users, dependent: :destroy
  has_many :users, through: :note_users, validate: false
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :list, dependent: :destroy
  has_one :log, dependent: :destroy
  has_one :reserve, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :character, uniqueness: { case_sensitive: false }
    validates :password
    validates :owner
    validates :owner_name
    validates :list_name
    validates :log_name
    validates :reserve_name
    validates :item_name
  end
  validates :genre_id, numericality: { other_than: 0 } 
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :owner_check, only: [:show, :edit, :destroy]

  def index
    @notes = User.find(current_user.id).notes
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    set_char
    if @note.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @note = Note.find(params[:character])
    redirect_to root_path unless @note.owner == current_user.id
    @user = User.find(params.require(:owner))
    if @note.update(edit_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def owner_check
    @note = Note.find_by(character: params[:character])
    redirect_to root_path unless @note.owner == current_user.id
  end

  def note_params
    params.require(:note).permit(:title, :genre_id, :list_name, :log_name, :reserve_name, :item_name, user_ids:[]).merge(owner: current_user.id, owner_name: current_user.nickname)
  end

  def edit_params
    params.require(:note).permit(:title, :genre_id, :list_name, :log_name, :reserve_name, :item_name).merge(owner: @user.id, owner_name: @user.nickname)
  end

  def set_char
    while @note.character.blank? || Note.find_by(character: @note.character).present? do
      @note.character = SecureRandom.alphanumeric(12)
    end
    @note.password = SecureRandom.alphanumeric(6)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="contents row">

    <%= form_with model: note, local: true do |f|%>
      <div class="field">
        <%= f.label :title, "ノートのタイトル" %><br />
        <%= f.text_field :title, id:"note_list" %>
      </div>
      <div class="field">
        <%= f.label :genre_id, "ジャンル" %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {}) %>
      </div>
      <div class="field">
        <%= f.label :list_name, "リストのタイトル" %><br />
        <%= f.text_field :list_name, id:"note_list" %>
      </div>
      <div class="field">
        <%= f.label :log_name, "履歴のタイトル" %><br />
        <%= f.text_field :log_name, id:"note_log" %>
      </div>
      <div class="field">
        <%= f.label :reserve_name, "予約のタイトル" %><br />
        <%= f.text_field :reserve_name, id:"note_reserve" %>
      </div>
      <div class="field">
        <%= f.label :item_name, "アイテム表のタイトル" %><br />
        <%= f.text_field :item_name, id:"note_item" %>
      </div>
      <input name="note[user_ids][]" type="hidden" value=<%= current_user.id %>>
      <div class="actions">
        <%= f.submit "作成する", class: :form__btn  %>
      </div>
    <% end %>

</div>

app/views/notes/_note.html.erb
<% if user_signed_in? %>
  <div class="card">
    <div class="card__body">
    <p class="card__summary"><%= note.title %></p>
      <div class="card__title"></div>
        <%= link_to "#{note.list_name}", note_lists_path(note.character), class: :card__title%>
        <%= link_to "#{note.item_name}", note_items_path(note.character), class: :card__title%>
        <%= link_to "#{note.log_name}", note_logs_path(note.character), class: :card__title%>
        <%= link_to "#{note.reserve_name}", note_reserves_path(note.character), class: :card__title%>
        <%= link_to "メッセージ", note_messages_path(note.character), class: :card__title%>
        <%= link_to "所有者 #{note.owner_name}", root_path, class: :card__user %>
        <% if note.owner == current_user.id %>
        <div class="prototype__manage">
          <%= link_to "招待", note_path(note.character), class: :card__btn %>
          <%= link_to "編集", edit_note_path(note.character), class: :card__btn %>
          <%= link_to "削除", note_path(note.character), method: :delete, data: { confirm: '対象ノートの全機能が削除されます、本当によろしいですか？' }, class: %w(card__btn delete__btn) %>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ノート編集</h2>
<div class="contents row">
  <div class="container">
    <%= form_with model: @note, local: true do |f|%>
      <div class="field">
        <%= f.label :title, "ノートのタイトル" %><br />
        <%= f.text_field :title, id:"note_list" %>
      </div>
      <div class="field">
        <%= f.label :genre_id, "ジャンル" %><br />
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {}) %>
      </div>
      <div class="field">
        <%= f.label :list_name, "リストのタイトル" %><br />
        <%= f.text_field :list_name, id:"note_list" %>
      </div>
      <div class="field">
        <%= f.label :log_name, "履歴のタイトル" %><br />
        <%= f.text_field :log_name, id:"note_log" %>
      </div>
      <div class="field">
        <%= f.label :reserve_name, "予約のタイトル" %><br />
        <%= f.text_field :reserve_name, id:"note_reserve" %>
      </div>
      <div class="field">
        <%= f.label :item_name, "アイテム表のタイトル" %><br />
        <%= f.text_field :item_name, id:"note_item" %>
      </div>
      <div class="field">
        <%= f.label :owner, "ノートの管理者(取扱注意)" %><br />
        <div class="guide">
          <input type="radio" id="hide" name="main" checked="checked">変更しない　
          <input type="radio" id="disp" name="main" >変更する
        </div>
        <div id="sub-form" style="display: none;">
          <select name="owner" id="owner-id">
          <option value=<%= current_user.id %>><%= current_user.nickname %></option>
          <% @note.users.where.not(id: current_user.id).each do |user| %>
          <option value=<%= user.id %>><%= user.nickname %></option>
          <% end %>
        </select>
        </div>
      </div>
      <input name="note_char" type="hidden" value=<%= @note.character %>>
      <div class="actions">
        <%= f.submit "保存する", class: :form__btn  %>
      </div>
    <% end %>
  </div>
</div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<main class="main">
<div class="bg__wrapper">
  <div class="inner">
    <div class="card__wrapper">
      <% if @notes == [] %>
        <div class="card">
          <div class="card__body">
            <p class="card__summary">ＢＡＧＥＲへ<br>ようこそ！</p>
            <br>
            <div class="card__title">
              ノート（メモ機能のセット）を作成・参加すると、<br>
              こちらに表示されます。<br><br>
              まずは「新規作成」から<br>
              作成してみましょう。
            </div>
            <br>
            <center>
            <%= link_to "新しいノートを作成！", new_note_path, class: :nav__btn %>
            </center><br>
          </div>
        </div>
      </div>
    <% else %>
      <%= render partial: 'note', collection: @notes %>
    <% end %>
    </div>
  </div>
</div>
</main>

app/views/notes/new.html.erb
<div class="bg__wrapper">
  <div class="contents row">
    <div class="container">
      <h2 class="page-heading">新規ノート投稿</h2>
        <%= render partial: "form", locals: { note: @note } %>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="bg__wrapper">
  <div class="contents row">
    <div class="container">
      <h1 id="top"><%= "#{@note.title}の招待ページ" %></h1>
      <p class="margin">「ノートに参加」ページで以下の情報を入力してください。</p>
      <table><tr>
        <td colspan="2"></td>
        </tr></tr>
        <td>ID</td>
        <td><%= "#{@note.character.slice(0..3)} #{@note.character.slice(4..7)} #{@note.character.slice(8..11)}" %></td>
        </tr><tr>
        <td>PASS</td>
        <td><%= "#{@note.password.slice(0..2)} #{@note.password.slice(3..5)}" %></td>
        </tr>
      </table>
      <p class="margin">以下のURL・QRコードからもアクセス可能です。</p>
      <div class="qr_code">
        <%= qrcode "http://6ager.com/guides/new?id=#{@note.character}&pass=#{@note.password}", {size: 6,  level: :h} %><br>
        <%= "http://6ager.com/guides/new?id=#{@note.character}&pass=#{@note.password}" %>
      </div>
    </div>
  </div>
</div>