config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'guides#index'
  resources :guides, only: [:index, :new, :create]
  resources :notes, param: :character do
    resources :items
    resources :lists, only: [:index, :new, :create, :update, :destroy]
    resources :logs, only: [:index, :show]
    resources :reserves, only: [:index, :new, :create, :show, :update, :destroy]
    resources :messages, only: :index
  end
  resources :users, only: [:edit, :update]
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :note
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :price
    validates :count
    validates :buyer
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @note = Note.find_by(character: params[:note_character])
    @logs = Log.where(note_id: @note.id)
  end

  def show
    @log = Log.find(params[:id])
    @note = Note.find_by(character: params[:note_character])
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_log.html.erb
<tr>
  <td><%= l log.created_at %></td>
  <td><%= "#{log.name}" %></td>
  <td><%= "#{log.price}" %></td>
  <td><%= "#{log.count}" %></td>
  <td><%= "#{log.condition}" %></td>
  <td><%= "#{log.memo}" %></td>
  <td><%= "#{log.buyer}" %></td>
  <td><%= link_to '詳細', note_log_path(id: log.id) %></td>
<tr>

app/views/logs/_splog.html.erb
<tr>
  <td rowspan="6"><%= l splog.created_at %><br>
    <%= "#{splog.buyer}" %><br><br>
    <%= link_to fa_icon("info-circle 2x"), note_log_path(id: splog.id) %>
  </td>
  <td><%= "名前：" %></td>
  <td><%= "#{splog.name}" %></td>
</tr>
<tr>
  <td><%= "値段：" %></td>
  <td><%= "#{splog.price}" %></td>
</tr>
<tr>
  <td><%= "個数：" %></td>
  <td><%= "#{splog.count}" %></td>
</tr>
<tr>
  <td><%= "条件：" %></td>
  <td><%= "#{splog.condition}" %></td>
</tr>
<tr>
  <td><%= "備考：" %></td>
  <td><%= "#{splog.memo}" %></td>
</tr>
<tr><td colspan="2"></td></tr>

app/views/logs/index.html.erb
<main class="main">
  <div class="inner">
  <h1><%= "#{@note.log_name}" %></h1>
      <% if @logs == [] %>
    <div class="none_item">
    <p>購入履歴がありません。</p>
    </div>
    <% else %>
    <table class="pc_table">
      <thead>
        <tr>
          <th>日付</th>
          <th>名前</th>
          <th>金額</th>
          <th>個数</th>
          <th>条件</th>
          <th>備考</th>
          <th>購入者</th>
          <th>編集</th>
        </tr>
      </thead>
      <tbody>
        <div>
          <%= render partial: 'log', collection: @logs %>
        </div>
      </tbody>
    </table>
    <table class="sp_table">
      <thead>
        <tr>
          <th>日付/購入者</th>
          <th colspan="2">情報</th>
        </tr>
      </thead>
      <tbody>
        <div>
          <%= render partial: 'splog', collection: @logs %>
        </div>
      </tbody>
    </table>
    <% end %>
        <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to note_lists_path(@note.character) do %>
          <input type="submit" value="リストへ戻る" class="sub__btn form__btn">
        <% end %>
      </div>
    <% end %>
  </div>
</main>

app/views/logs/show.html.erb
<main class="main bg_gray">
  <div class="contents row">
    <div class="container no_opacity">
      <p class="prototype__hedding margin">
        <%= @log.name %>
      </p>
      <div>
        <table>
          <tr>
            <td colspan="2"></td>
          </tr><tr> 
          <tr>
            <td><p class="detail__title"><%= "購入日時" %></p></td>
            <td><p class="detail__title"><%= l @log.created_at %></p>
          </tr><tr>
            <td><p class="detail__title"><%= "購入者" %></p></td>
            <td><p class="detail__title"><%= @log.buyer %></p></td>
          </tr><tr>
            <td><p class="detail__title"><%= "購入価格" %></p></td>
            <td><p class="detail__title"><%= @log.price %></p></td>
          </tr><tr>
            <td><p class="detail__title"><%= "購入個数" %></p></td>
            <td><p class="detail__title"><%= @log.count %></p></td>
          </tr><tr>
            <td><p class="detail__title"><%= "購入条件" %></p></td>
            <td><p class="detail__title"><%= @log.condition %></p></td>
          </tr><tr>
            <td><p class="detail__title"><%= "備考" %></p></td>
            <td><p class="detail__title"><%= @log.memo %></p></td>
          </tr>
        </table>
      </div>
    </div>
    <%= link_to :back do %>
      <input type="submit" value="戻る" class="form__btn">
    <% end %>
  </div>
</main>