config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'guides#index'
  resources :guides, only: [:index, :new, :create]
  resources :notes, param: :character do
    resources :items
    resources :lists, only: [:index, :new, :create, :update, :destroy]
    resources :logs, only: [:index, :show]
    resources :reserves, only: [:index, :new, :create, :show, :update, :destroy]
    resources :messages, only: :index
  end
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: '以下から選択' },
    { id: 1, name: '買い物' },
    { id: 2, name: '旅行' },
    { id: 3, name: '仕事' },
    { id: 4, name: '趣味' },
    { id: 5, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :notes
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :note
  belongs_to :user
  has_one :list
  has_many :logs
  has_many :reserves
  has_one_attached :image

  with_options presence: true do
    validates :name
    with_options numericality: true do
      validates :price
      validates :count
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :note
  belongs_to :item
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :note
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :price
    validates :count
    validates :buyer
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :note
  has_one_attached :image

  validates :content, presence: true #, unless: :was_attached?
  after_create_commit { MessageBroadcastJob.perform_later self }

  def was_attached?
    self.image.attached?
  end
end

app/models/next.rb
class Next < ActiveHash::Base
  self.data = [
    { id: 0, name: '未定' },
    { id: 1, name: '1日' },
    { id: 2, name: '2日' },
    { id: 3, name: '3日' },
    { id: 4, name: '4日' },
    { id: 5, name: '5日' },
    { id: 6, name: '6日' },
    { id: 7, name: '1週間' },
    { id: 8, name: '2週間' },
    { id: 9, name: '3週間' },
    { id: 10, name: '1ヶ月' },
    { id: 11, name: '2ヶ月' },
    { id: 12, name: '3ヶ月' },
    { id: 13, name: '半年' },
    { id: 14, name: '1年' },
  ]

  include ActiveHash::Associations
  has_many :reserves
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_users, dependent: :destroy
  has_many :users, through: :note_users, validate: false
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :list, dependent: :destroy
  has_one :log, dependent: :destroy
  has_one :reserve, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  with_options presence: true do
    validates :character, uniqueness: { case_sensitive: false }
    validates :password
    validates :owner
    validates :owner_name
    validates :list_name
    validates :log_name
    validates :reserve_name
    validates :item_name
  end
  validates :genre_id, numericality: { other_than: 0 } 
end

app/models/note_user.rb
class NoteUser < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/once.rb
class Once < ActiveHash::Base
  self.data = [
    { id: 0, name: '定期的' },
    { id: 1, name: '不定期' },
    { id: 2, name: '今回限り' },
  ]

  include ActiveHash::Associations
  has_many :reserves
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :note
  belongs_to :item
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :next
  belongs_to :once

  with_options presence: true do
    validates :date
    validates :next_id
    validates :once_id
  end

  def self.date_check
    all.each do |reserve|
      if reserve.date <= Date.today
        if List.find_by(item_id: reserve.item_id) == nil
          @list = List.new
          @list.note_id = reserve.note_id
          @list.item_id = reserve.item_id
          @list.save
          reserve.check_once
        end
      end
    end
  end

  def set_date
    case self.next_id
    when 0
      self.date = Date.today.next_year(1000)
    when 1
      self.date = Date.tomorrow
    when 2
      self.date = Date.today.next_day(2)
    when 3
      self.date = Date.today.next_day(3)
    when 4
      self.date = Date.today.next_day(4)
    when 5
      self.date = Date.today.next_day(5)
    when 6
      self.date = Date.today.next_day(6)
    when 7
      self.date = Date.today.next_day(7)
    when 8
      self.date = Date.today.next_day(14)
    when 9
      self.date = Date.today.next_day(21)
    when 10
      self.date = Date.today.next_month
    when 11
      self.date = Date.today.next_month(2)
    when 12
      self.date = Date.today.next_month(3)
    when 13
      self.date = Date.today.next_month(6)
    else
      self.date = Date.today.next_year
    end
  end

  def check_once
    case self.once_id
    when 0
      set_date
      self.save
    when 1
      self.next_id = 0
      self.date = Date.today.next_year(1000)
      self.save
    else
      self.destroy
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Input half-width alphanumeric characters.'

  with_options presence: true do
    validates :first_name
    validates :last_name
    validates :nickname
  end

  has_many :note_users, dependent: :destroy
  has_many :notes, through: :note_users
  has_many :items
  has_many :messages

  def self.count_reset
    all.each do |user|
      if user.count > 0 
        user.update_attribute(:count, 0)
      end
    end
  end

  def self.stop_down
    all.each do |user|
      if user.stop > 0 
        user.update_attribute(:stop, user.stop - 1)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def qrcode(text, options = {})
    ::RQRCode::QRCode.new(text, options).as_svg(
      module_size: 6
    ).html_safe
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon-180x180.png">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </head>

  <body>
  <% if user_signed_in? %>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("/images/logo.png", class: :logo), root_path %>
          </div>
          <div class="head__box">
            <div class="greeting">
              <%= 'こんにちは、' %>
              <%= link_to "#{current_user.nickname}さん", root_path, class: :greeting__link%>
            </div>
          </div>
          <div class="head__box">
            <%= link_to "新規作成", new_note_path, class: :nav__btn %>
            <%= link_to "ノート参加", new_guide_path, class: :nav__btn %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: :nav__logout %>
          </div>
          <div class="icon__box">
            <%= link_to fa_icon("folder-plus 2x"), new_note_path, class: :nav__btn %>
            <%= link_to fa_icon("sign-in-alt 2x"), new_guide_path, class: :nav__btn %>
            <%= link_to fa_icon("door-open 2x"), destroy_user_session_path, method: :delete,class: :nav__btn %>
          </div>
        </div>
      </div>
    </header>
    <% end %>
    <script>
      $(function(){
        setInterval(function() {
        $(".alert").fadeOut(1000);
        $(".notice").fadeOut(1000);
        }, 3000);
      });
    </script>
    <div class="yield">
        <div class="notifications">
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: key) %>
    <% end %>
    </div>
    <%= yield %>
    </div>
    <footer class="footer">
      <p class="copyright">Copyright © BAGER All rights reserved.</p>
    </footer>
  </body>
</html>